# Generated by Django 5.1.4 on 2024-12-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('permanent_address', models.CharField(blank=True, max_length=255, null=True)),
                ('current_address', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('passport', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.CharField(max_length=15)),
                ('pan_no', models.CharField(blank=True, max_length=50, null=True)),
                ('visa', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True , unique=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_number', models.CharField(max_length=15,blank=True, null=True)),
                ('relocation_availability', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
